tasks:
  - name: ollama
    command: |
      curl -fsSL https://ollama.com/install.sh | sh
      clear && ollama serve

  - name: n8n
    command: |
      npm install n8n -g
      clear && n8n start --tunnel

  - name: open-webui
    command: |
      pip install open-webui
      clear && open-webui serve

  - name: open-webui
    command: clear && docker run -d -p 9099:9099 --network=host --add-host=host.docker.internal:host-gateway -v pipelines:/app/pipelines --name pipelines --restart always ghcr.io/open-webui/pipelines:main